---
- hosts: all
  user: vagrant
  sudo: yes
  tasks:
    - name: Installs nginx web server
      apt: pkg=nginx state=installed update_cache=true
      notify:
        - start nginx

    - name: install python dev
      sudo: yes
      apt: pkg={{ item }} state=present
      with_items:
        - python3-setuptools
        - python3.4-venv
        - python3-dev
        - python3-pip
        - build-essential
        - libjack-jackd2-dev
        - portaudio19-dev
        - git

    - name: Install pip requirements
      pip:
        requirements: /srv/speechy/requirements.txt
        virtualenv: /srv/speechy_env
        virtualenv_python: python3.4

  handlers:
    - name: start nginx
      service: name=nginx state=started
