---
- hosts: all
  user: vagrant
  sudo: yes
  tasks:
    - name: Installs nginx web server
      apt: pkg=nginx state=installed
      notify:
        - start nginx

    - name: create self-signed SSL cert
      command: openssl req -new -nodes -x509 -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN=${ansible_fqdn}" -days 3650 -keyout /etc/ssl/certs/server.key -out /etc/ssl/certs/server.crt -extensions v3_ca creates=/etc/ssl/certs/server.crt
      notify: reload nginx

    - name: install python dev
      sudo: yes
      apt: pkg={{ item }} state=present
      with_items:
        - python3-setuptools
        - python3.4-venv
        - python3-dev
        - python3-pip
        - build-essential
        - libjack-jackd2-dev
        - portaudio19-dev
        - git
        - espeak

    - name: Install pip requirements
      pip:
        requirements: /srv/speechy/requirements.txt
        virtualenv: /srv/speechy_env
        virtualenv_python: python3.4

    - name: Setup upstart
      sudo: yes
      command: cp /srv/speechy/confs/upstart /etc/init/speechy.conf

    - file: path=/etc/init/speechy.conf owner=root group=root mode=0644

  handlers:
    - name: start nginx
      service: name=nginx state=started
